generated
reduceTable
^#(
	#(14 0 #reduceActionForQUOTEDCODEPART_1:) 
	#(11 1 #reduceFor:) 
	#(9 1 #reduceActionForSTRINGPART1:) 
	#(12 1 #reduceActionForNORMALVAR1:) 
	#(9 1 #reduceActionForSTRINGPART3:) 
	#(8 1 #reduceActionForSPLICECOMPOUND1:) 
	#(17 1 #liftFirstValue:) 
	#(7 1 #liftFirstValue:) 
	#(14 2 #reduceActionForQUOTEDCODEPART_2:) 
	#(15 1 #reduceActionForTYPE1:) 
	#(16 1 #reduceActionForTYPE_1:) 
	#(13 2 #reduceActionForDECORATEDVAR1:) 
	#(16 2 #reduceActionForQUOTEDCODEPART_2:)
	).