Class {
	#name : #ConcreteSubClass,
	#superclass : #TestClass3,
	#category : 'LiCoR-Tests'
}

{ #category : #'instance creation' }
ConcreteSubClass class >> new [
	"Answer a newly created and initialized instance."

	
	^super new initialize
]

{ #category : #testing }
ConcreteSubClass >> anAbstractMethod [
	
	
]

{ #category : #testing }
ConcreteSubClass >> anotherAbstractMethod [
	
	
]

{ #category : #testing }
ConcreteSubClass >> doNotOverride [
	
	
]
